name: localstack

services:
  localstack:
    container_name: localstack
    image: docker.io/localstack/localstack:latest
    ports:
      - 4566:4566
    environment:
      DEBUG: ${DEBUG:-1}
      SERVICES: ${SERVICES:-s3}
    volumes:
      - type: bind
        source: ./scripts
        target: /root/localstack
        read_only: true
