name: localstack

services:
  localstack:
    container_name: localstack
    image: docker.io/localstack/localstack:3.2.0
    ports:
      - 4566:4566
    environment:
      - DEBUG=${DEBUG:-1}
      - SERVICES=${SERVICES:-s3}
    volumes:
      - ./data:/var/lib/localstack
      - type: bind
        source: ./scripts
        target: /root/localstack
        read_only: true
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
